export const BRAND_IMAGE_LOCAL_STORAGE_KEY = 'BRAND_IMAGE_LOCAL_STORAGE_KEY';
export const PRODUCT_IMAGE_LOCAL_STORAGE_KEY = 'PRODUCT_IMAGE_LOCAL_STORAGE_KEY';

// Home Controller Tab Strings
export const HOME_TAB_WEEKLY = 'HOME_TAB_WEEKLY'
export const HOME_TAB_MONTHLY = 'HOME_TAB_MONTHLY'
export const HOME_TAB_YEARLY = 'HOME_TAB_YEARLY'